import pygame

#DEBUG
DEBUG = False

#Display
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 400
DISPLAYSURF = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
#DISPLAYSURF.fill(GREEN)

#Grid
GRID_DIM_WIDTH = 40 * 5
GRID_DIM_HEIGHT = 4 * 5

#Frames
FramePerSec = pygame.time.Clock()
FPS = 60

#Tiles
BLANK, UP, RIGHT, DOWN, LEFT = 0, 1, 2, 3, 4
ALL_OPTIONS = {BLANK, UP, RIGHT, DOWN, LEFT}
SPRITE_SIZE_W, SPRITE_SIZE_H = SCREEN_WIDTH // GRID_DIM_WIDTH, SCREEN_HEIGHT // GRID_DIM_HEIGHT
TILE_SET = "circles"
TILE_WEIGHTS = {"black": 1, "white": 1}